apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: example-application
    namespace: argocd # Namespace where ArgoCD is installed
spec:
    project: default
    source:
        repoURL: https://github.com/carlosanjos/web-app.git
        targetRevision: HEAD
        path: dev
    destination:
        server: https://kubernetes.default.svc
        namespace: dev # Namespace where the application will be deployed
    syncPolicy:
        -CreateNamespace: true # Automatically create the namespace if it doesn't exist
        automated:
            SelfHeal: true
            Prune: true
