apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: example-application
    namespace: argocd # Namespace where ArgoCD is installed
spec:
    project: default
    source:
        repoURL: https://github.com/carlosanjos/web-app.git
        targetRevision: HEAD
        path: dev
    destination:
        server: https://kubernetes.default.svc
        namespace: dev # Namespace where the application will be deployed
    syncPolicy:
        syncOptions:
            - CreateNamespace=true # Automatically create the namespace if it doesn't exist
        automated:
            selfHeal: true # Automatically heal the application if it drifts from the desired state
            prune: true # Automatically prune resources that are no longer defined in the source
