apiVersion: v1
kind: PersistentVolume
metadata:
    name: nginx-static-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: nas
    nfs:
        server: 192.168.0.210 # Replace with your NAS server IP
        path: /mnt/nvme/web-app # Fixed, predictable path on the NAS
