apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nginx-test-nas
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: nas
    volumeName: nginx-static-pv
